// @ts-nocheck
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Receives the result of a `YARDSORT_BENCH` run, prints it as one line of JSON and quits. */
	benchReport: (report: string) => __TAURI_INVOKE<void>("bench_report", { report }),
	projectsList: () => typedError<Project[], IpcError>(__TAURI_INVOKE("projects_list")),
	/**  Add the repository containing `path`. Fails with `not_a_git_repo` unless `init_git` is set. */
	projectOpen: (path: string, initGit: boolean) => typedError<AddedProject, IpcError>(__TAURI_INVOKE("project_open", { path, initGit })),
	projectCreate: (name: string, parent: string) => typedError<AddedProject, IpcError>(__TAURI_INVOKE("project_create", { name, parent })),
	/**
	 *  Take a project off the list. With `keep_history` its workspaces and their conversations
	 *  wait for the folder to be opened again. Files on disk are never touched.
	 */
	projectRemove: (id: string, keepHistory: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("project_remove", { id, keepHistory })),
	projectsReorder: (orderedIds: string[]) => typedError<null, IpcError>(__TAURI_INVOKE("projects_reorder", { orderedIds })),
	uiStateLoad: () => typedError<{ [key in string]: string }, IpcError>(__TAURI_INVOKE("ui_state_load")),
	uiStateSave: (key: string, value: string) => typedError<null, IpcError>(__TAURI_INVOKE("ui_state_save", { key, value })),
	harnessesList: () => typedError<HarnessInfo[], IpcError>(__TAURI_INVOKE("harnesses_list")),
	/**
	 *  Save a harness definition. For a built-in only the differences from the shipped definition
	 *  are stored; saving one identical to it removes the override.
	 */
	harnessSave: (def: HarnessDef) => typedError<HarnessInfo[], IpcError>(__TAURI_INVOKE("harness_save", { def })),
	/**  Restore a built-in to its shipped definition, or delete a custom harness. */
	harnessReset: (id: string) => typedError<HarnessInfo[], IpcError>(__TAURI_INVOKE("harness_reset", { id })),
	/**  What would run for this — possibly unsaved — definition, with sample values filled in. */
	harnessPreview: (def: HarnessDef) => typedError<HarnessPreview, IpcError>(__TAURI_INVOKE("harness_preview", { def })),
	/**
	 *  Start this — possibly unsaved — definition in the home directory, with no prompt, to see
	 *  whether it comes up. The caller shows the session and closes it.
	 */
	harnessTest: (def: HarnessDef, size: TermSize) => typedError<SessionInfo, IpcError>(__TAURI_INVOKE("harness_test", { def, size })),
	settingsGet: () => typedError<SettingsInfo, IpcError>(__TAURI_INVOKE("settings_get")),
	settingsSaveWorkspaces: (workspaces: WorkspaceSettingsDto) => typedError<SettingsInfo, IpcError>(__TAURI_INVOKE("settings_save_workspaces", { workspaces })),
	settingsSaveGeneral: (editorCommand: string | null, notifyWhenQuiet: boolean, checkForUpdates: boolean) => typedError<SettingsInfo, IpcError>(__TAURI_INVOKE("settings_save_general", { editorCommand, notifyWhenQuiet, checkForUpdates })),
	projectBranches: (projectId: string) => typedError<BranchList, IpcError>(__TAURI_INVOKE("project_branches", { projectId })),
	/**
	 *  The core loop: make a worktree — on a new branch, or for an existing one — and start a harness in it with the user's
	 *  first message. If the harness cannot start, the worktree and branch are taken back, so a
	 *  failed attempt leaves no trace.
	 */
	workspaceCreate: (request: NewWorkspace) => typedError<CreatedWorkspace, IpcError>(__TAURI_INVOKE("workspace_create", { request })),
	/**  Remove a workspace's worktree. The branch is kept. Fails with `worktree_dirty` unless `force`. */
	workspaceDelete: (id: string, force: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("workspace_delete", { id, force })),
	workspaceChanges: (workspaceId: string) => typedError<ChangeSet, IpcError>(__TAURI_INVOKE("workspace_changes", { workspaceId })),
	workspaceDiff: (workspaceId: string, path: string, oldPath: string | null, scope: Scope) => typedError<FileDiff, IpcError>(__TAURI_INVOKE("workspace_diff", { workspaceId, path, oldPath, scope })),
	/**
	 *  One folder of the workspace's file tree (`dir` is relative; empty for the root). With
	 *  `show_ignored`, `.git` and ignored entries are included and flagged.
	 */
	workspaceFiles: (workspaceId: string, dir: string, showIgnored: boolean) => typedError<FileEntry[], IpcError>(__TAURI_INVOKE("workspace_files", { workspaceId, dir, showIgnored })),
	workspaceFile: (workspaceId: string, path: string) => typedError<Content, IpcError>(__TAURI_INVOKE("workspace_file", { workspaceId, path })),
	/**  Watch this workspace's files (replacing any previous watch); `None` stops watching. */
	workspaceWatch: (workspaceId: string | null) => typedError<null, IpcError>(__TAURI_INVOKE("workspace_watch", { workspaceId })),
	/**  Open a file (or the workspace folder, when `path` is `None`) in the user's editor. */
	openInEditor: (workspaceId: string, path: string | null) => typedError<null, IpcError>(__TAURI_INVOKE("open_in_editor", { workspaceId, path })),
	assistStatus: () => typedError<AssistStatus, IpcError>(__TAURI_INVOKE("assist_status")),
	/**
	 *  Save an API key, once TypeSafe confirms it works. It goes to the OS credential store and is
	 *  never sent back to the webview.
	 */
	assistSaveKey: (key: string) => typedError<AssistStatus, IpcError>(__TAURI_INVOKE("assist_save_key", { key })),
	assistForgetKey: () => typedError<AssistStatus, IpcError>(__TAURI_INVOKE("assist_forget_key")),
	/**  Ask TypeSafe whether the key in force still works. */
	assistTestKey: () => typedError<null, IpcError>(__TAURI_INVOKE("assist_test_key")),
	assistSaveSettings: (reviewChanges: boolean, suggestInComposer: boolean, thresholds: ThresholdsDto) => typedError<AssistStatus, IpcError>(__TAURI_INVOKE("assist_save_settings", { reviewChanges, suggestInComposer, thresholds })),
	/**
	 *  Check a workspace's changed files against what was asked, and for risky edits. Sends the
	 *  diffs of those files to TypeSafe.
	 */
	assistReview: (workspaceId: string) => typedError<Review, IpcError>(__TAURI_INVOKE("assist_review", { workspaceId })),
	/**
	 *  Suggest a harness and an effort for the message being typed. Sends the message and the
	 *  harnesses' "Good at" descriptions.
	 */
	assistSuggest: (message: string) => typedError<Suggestion, IpcError>(__TAURI_INVOKE("assist_suggest", { message })),
	sessionsList: (workspaceId: string) => typedError<SessionRecord[], IpcError>(__TAURI_INVOKE("sessions_list", { workspaceId })),
	/**  Continue a conversation whose process has ended, in a new terminal. */
	sessionResume: (id: string, size: TermSize) => typedError<SessionInfo, IpcError>(__TAURI_INVOKE("session_resume", { id, size })),
	/**  Start a copy of a conversation — running or not — that goes its own way from here. */
	sessionFork: (id: string, size: TermSize) => typedError<SessionInfo, IpcError>(__TAURI_INVOKE("session_fork", { id, size })),
	/**  Drop a record from the history. The harness's own copy of the conversation is not touched. */
	sessionForget: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("session_forget", { id })),
	/**
	 *  Put a workspace away: the worktree is removed, the branch and session history stay.
	 *  Fails with `worktree_dirty` unless `force`.
	 */
	workspaceArchive: (id: string, force: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("workspace_archive", { id, force })),
	/**  Bring back an archived workspace, or one whose folder disappeared, at its old path. */
	workspaceRestore: (id: string) => typedError<Workspace, IpcError>(__TAURI_INVOKE("workspace_restore", { id })),
	workspaceRename: (id: string, name: string) => typedError<Workspace, IpcError>(__TAURI_INVOKE("workspace_rename", { id, name })),
	/**
	 *  Worktrees of the project that are not workspaces — made by hand, by another tool, or
	 *  forgotten here — for the import dialog.
	 */
	projectUntrackedWorktrees: (projectId: string) => typedError<UntrackedWorktree[], IpcError>(__TAURI_INVOKE("project_untracked_worktrees", { projectId })),
	/**  Make workspaces of the untracked worktrees at `paths`. Nothing on disk is touched. */
	workspacesImport: (projectId: string, paths: string[]) => typedError<Workspace[], IpcError>(__TAURI_INVOKE("workspaces_import", { projectId, paths })),
	/**
	 *  Stop showing a workspace. Its folder and branch stay; with `keep_history` its conversations
	 *  do too, ready for the day it is imported again.
	 */
	workspaceForget: (id: string, keepHistory: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("workspace_forget", { id, keepHistory })),
	/**  With `reload`, the login shell is asked again first — for "I just installed it, look again". */
	preflight: (reload: boolean) => typedError<Preflight, IpcError>(__TAURI_INVOKE("preflight", { reload })),
	/**  Ask whether a newer release exists. Touches nothing on disk. */
	updateCheck: () => typedError<UpdateStatus, IpcError>(__TAURI_INVOKE("update_check")),
	/**
	 *  Download the update found by the last check, verify its signature, install it and restart.
	 *  Only for [`InstallKind::SelfUpdating`] copies.
	 */
	updateInstall: (progress: Channel<DownloadProgress>) => typedError<null, IpcError>(__TAURI_INVOKE("update_install", { progress })),
	envInfo: (reload: boolean) => typedError<EnvInfo, IpcError>(__TAURI_INVOKE("env_info", { reload })),
	/**
	 *  What the app is talking to. Shown in the status bar, and the first thing worth knowing when
	 *  a terminal misbehaves.
	 */
	daemonStatus: () => typedError<DaemonStatus, IpcError>(__TAURI_INVOKE("daemon_status")),
	/**
	 *  The user's answer. `stop_agents` kills everything the daemon runs and stops it; otherwise the
	 *  agents are left to carry on and the app simply lets go of them.
	 */
	appQuit: (stopAgents: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("app_quit", { stopAgents })),
	/**
	 *  Let the next close request ask again. Called when the user cancels, so that closing the
	 *  window later still puts the question.
	 */
	quitCancelled: () => typedError<null, IpcError>(__TAURI_INVOKE("quit_cancelled")),
	ptySpawn: (request: SpawnRequest) => typedError<SessionInfo, IpcError>(__TAURI_INVOKE("pty_spawn", { request })),
	/**  Stream a session into `output`: first a snapshot that repaints the terminal, then live bytes. */
	ptyAttach: (id: SessionId, output: Channel<RawBytes>) => typedError<number, IpcError>(__TAURI_INVOKE("pty_attach", { id, output })),
	ptyDetach: (id: SessionId, attachment: number) => typedError<null, IpcError>(__TAURI_INVOKE("pty_detach", { id, attachment })),
	ptyWrite: (id: SessionId, data: string) => typedError<null, IpcError>(__TAURI_INVOKE("pty_write", { id, data })),
	ptyResize: (id: SessionId, size: TermSize) => typedError<null, IpcError>(__TAURI_INVOKE("pty_resize", { id, size })),
	ptyKill: (id: SessionId) => typedError<null, IpcError>(__TAURI_INVOKE("pty_kill", { id })),
	/**  Kill (if needed) and forget a session. */
	ptyClose: (id: SessionId) => typedError<null, IpcError>(__TAURI_INVOKE("pty_close", { id })),
	ptyList: () => typedError<SessionInfo[], IpcError>(__TAURI_INVOKE("pty_list")),
};

/** Events */
export const events = {
	ptyHostEvent: makeEvent<PtyHostEvent>("pty-host-event"),
	quitRequested: makeEvent<QuitRequested>("quit-requested"),
	workspaceFilesChanged: makeEvent<WorkspaceFilesChanged>("workspace-files-changed"),
};

/* Types */
/**  The result of adding a project: it may have been known already. */
export type AddedProject = {
	project: Project,
	alreadyKnown: boolean,
	/**  Set when the chosen folder was inside a repository and its root was added instead. */
	openedRootInstead: boolean,
	/**
	 *  Set when the folder was a project removed earlier with its history kept: it is back
	 *  with its workspaces and their conversations.
	 */
	revived: boolean,
};

/**  Static facts about the running app, shown in the UI and useful in bug reports. */
export type AppInfo = {
	name: string,
	version: string,
	/**  `linux`, `macos` or `windows`. */
	os: string,
	arch: string,
	debug: boolean,
	dev: DevFlags,
};

export type AssistStatus = {
	keySource: KeySource,
	/**  The end of the key in force, so it can be told apart without being shown. */
	keyHint: string | null,
	/**  Why the credential store could not be used, if it could not. */
	problem: string | null,
	reviewChanges: boolean,
	suggestInComposer: boolean,
	/**  How sure Jev must be before an answer becomes a badge or a suggestion. */
	thresholds: ThresholdsDto,
	/**  The model every request names. */
	model: string,
};

export type AvailableUpdate = {
	version: string,
	/**  The release notes, as written on the release. */
	notes: string | null,
	/**  Where to read about it and download it by hand. */
	url: string,
};

export type BranchList = {
	branches: string[],
	/**  The branch to offer first: the remote's default, or the one checked out. */
	default: string | null,
	/**
	 *  Branches checked out in some worktree already. Git allows a branch in one place only, so
	 *  these cannot be opened as a workspace.
	 */
	checkedOut: string[],
};

export type ChangeKind = "added" | "modified" | "deleted" | "renamed" | 
/**  New and not yet known to git. */
"untracked" | "conflicted";

export type ChangeSet = {
	uncommitted: FileChange[],
	committed: FileChange[],
	/**
	 *  The branch `committed` is measured against; `None` when there is nothing to compare with
	 *  (the workspace *is* the base branch, or HEAD is detached).
	 */
	base: string | null,
};

export type Content = 
/**  The file does not exist on this side (added, or deleted). */
{ type: "absent" } | { type: "text"; text: string } | { type: "binary" } | { type: "tooLarge"; bytes: number };

export type CreatedWorkspace = {
	workspace: Workspace,
	session: SessionInfo,
};

/**  What the app ended up talking to, as the status bar and a bug report want it. */
export type DaemonStatus = {
	/**
	 *  False when terminals are running inside the app instead — `YARDSORT_NO_DAEMON`, or a
	 *  daemon that could not be reached. They then die with the app, as they did before.
	 */
	running: boolean,
	version: string | null,
	pid: number | null,
	/**  Where the daemon listens, and where it writes when something goes wrong. */
	endpoint: string,
	logPath: string,
	/**  Why there is no daemon, when there should have been one. */
	problem: string | null,
	/**
	 *  Set when a daemon is running that this build cannot talk to — the app was updated
	 *  underneath agents that are still working. It says how many, so they can be asked about
	 *  rather than stopped behind the user's back.
	 */
	strandedSessions: number | null,
};

/**
 *  Switches for measuring and debugging, read from the environment. Always empty in release
 *  builds.
 */
export type DevFlags = {
	/**
	 *  `YARDSORT_BENCH`: a shell script to run in a terminal while frame times are recorded;
	 *  the app prints the result and exits. See `docs/design/07-terminal-benchmarks.md`.
	 */
	bench: string | null,
	/**
	 *  `YARDSORT_BENCH_LATENCY`: time keystroke round trips in a terminal instead of running a
	 *  script, then print the result and exit. Takes precedence over `bench`.
	 */
	benchLatency: boolean,
	/**  `YARDSORT_RENDERER`: force the terminal renderer (`webgl` or `dom`). */
	renderer: string | null,
};

export type DownloadProgress = {
	downloaded: number,
	/**  `None` when the server did not say how big the download is. */
	total: number | null,
};

/**  What the launch environment looks like, for the status bar and for bug reports. */
export type EnvInfo = {
	source: EnvSource,
	shell: string,
	pathEntries: number,
	warning: string | null,
};

export type EnvSource = 
/**  Captured from the user's login shell. */
"loginShell" | 
/**  This process's own environment: always on Windows, and the fallback elsewhere. */
"process";

export type ExitInfo = {
	code: number,
	success: boolean,
	/**  Name of the terminating signal, where the platform reports one. */
	signal: string | null,
};

export type FileChange = {
	/**  Path relative to the workspace root, with `/` separators. */
	path: string,
	/**  Where a renamed file used to live. */
	oldPath: string | null,
	kind: ChangeKind,
	/**  Lines added / removed. `None` for binary and untracked files. */
	additions: number | null,
	deletions: number | null,
};

export type FileDiff = {
	old: Content,
	new: Content,
};

export type FileEntry = {
	name: string,
	/**  Relative to the workspace root, with `/` separators. */
	path: string,
	isDir: boolean,
	/**  Excluded by the ignore rules (or `.git` itself). Only ever listed on request. */
	ignored: boolean,
};

export type FileReview = {
	path: string,
	scope: Scope,
	/**  `None` when the workspace's task is not known, or the file was not checked. */
	relevance: Relevance | null,
	flags: ReviewFlag[],
	/**  Why this file was not looked at, if it was not. */
	notChecked: string | null,
};

export type GitStatus = {
	path: string | null,
	/**  As `git --version` prints it, e.g. `git version 2.55.0`. */
	version: string | null,
};

export type HarnessDef = {
	/**  Stable key, recorded with sessions. */
	id: string,
	label: string,
	command: string,
	/**  Always passed. */
	baseArgs: string[],
	modelArgs: string[],
	effortArgs: string[],
	sessionArgs: string[],
	promptArgs: string[],
	resumeArgs: string[],
	forkArgs: string[],
	/**  Effort levels to offer. Empty hides the picker. */
	efforts: string[],
	/**  Model suggestions. Free text is always accepted: names change faster than we ship. */
	models: string[],
	promptTransport: PromptTransport,
	sessionIdMode: SessionIdMode,
	/**
	 *  With the `stdin` transport: how long the harness must have been quiet, after printing
	 *  something, before the prompt is pasted.
	 */
	stdinReadyMs: number,
	/**  Disabled harnesses stay configured but are not offered. */
	enabled: boolean,
	/**
	 *  In the user's words, what this harness is good at. Assist uses it to suggest a harness
	 *  for a task; harnesses without one are never suggested. Empty for every built-in: which
	 *  agent suits which work is the user's call, not ours.
	 */
	strengths?: string,
};

/**  A harness definition plus whether its command can be found on this machine. */
export type HarnessInfo = {
	/**  Where `command` resolved to on the user's `PATH`; `None` if it is not installed. */
	resolvedPath: string | null,
	/**  Ships with Yardsort (as opposed to one the user added). */
	builtin: boolean,
	/**  A built-in whose definition the user has changed. */
	modified: boolean,
} & HarnessDef;

/**  The exact command lines a definition produces, for the settings form to show. */
export type HarnessPreview = {
	resolvedPath: string | null,
	start: string[],
	resume: string[],
	fork: string[],
	/**  Why this definition cannot be saved as it stands, if it cannot. */
	problem: string | null,
};

/**  Which harness to start, and with what. */
export type HarnessRequest = {
	id: string,
	/**  `None` or empty: let the harness use its own default. */
	model: string | null,
	effort: string | null,
	/**  The first message. `None` or empty just opens the harness. */
	prompt: string | null,
};

export type HarnessStatus = {
	id: string,
	label: string,
	command: string,
	enabled: boolean,
	/**  Where the command was found; `None` if it is not installed (or not on `PATH`). */
	path: string | null,
	/**  How to get it. Known for the built-in harnesses only. */
	install: InstallHint | null,
};

export type HeadInfo = {
	/**  Branch name, or the abbreviated commit when detached. */
	label: string,
	detached: boolean,
	/**  The branch has no commits yet. */
	unborn: boolean,
};

/**  Host-wide notifications, delivered to the sink given to [`crate::PtyHost::new`]. */
export type HostEvent = 
/**  The session's process ended and all of its output has been delivered. */
{ type: "exited"; id: SessionId; exit: ExitInfo } | 
/**  The session started producing output after being quiet. */
{ type: "busy"; id: SessionId } | 
/**
 *  The session has printed nothing for the host's quiet period: whatever runs in it is
 *  probably waiting for input. `busy_ms` is how long the burst of activity lasted, which
 *  lets a client tell an agent finishing minutes of work from the echo of a keystroke.
 */
{ type: "quiet"; id: SessionId; busyMs: number };

export type InstallHint = {
	/**  One command that installs it on any OS with Node.js. */
	command: string,
	/**  The project's own install instructions, for every other way. */
	url: string,
};

/**  How this copy of the app gets new versions. */
export type InstallKind = 
/**  It can download and install an update itself. */
"selfUpdating" | 
/**  A package manager owns the files; the user updates through it. */
"packageManager" | 
/**  A development build. Never updates. */
"development";

/**
 *  The one error shape that crosses IPC: a stable `code` for the UI to branch on and a
 *  human-readable `message` to show.
 */
export type IpcError = {
	code: string,
	message: string,
};

export type KeySource = "none" | 
/**  Saved from Settings, in the OS credential store. */
"keychain" | 
/**  `TYPESAFE_API_KEY`, from the environment Yardsort runs in. */
"environment";

export type NewWorkspace = {
	projectId: string,
	/**  `None` starts from the project's default branch. */
	baseBranch: string | null,
	/**  Open this existing branch instead of creating a new one; `base_branch` is then ignored. */
	existingBranch: string | null,
	harness: HarnessRequest,
	size: TermSize,
};

export type Preflight = {
	git: GitStatus,
	harnesses: HarnessStatus[],
	env: EnvInfo,
	/**  `linux`, `macos` or `windows`: install advice differs. */
	os: string,
	/**  Nothing stands between the user and their first workspace. */
	ready: boolean,
};

export type Project = {
	id: string,
	name: string,
	rootPath: string,
	/**
	 *  The folder is gone (deleted, moved, or on an unmounted drive). The project is kept so it
	 *  reappears by itself if the folder does; the user can remove it.
	 */
	missing: boolean,
	workspaces: Workspace[],
};

export type PromptTransport = 
/**  The prompt is an argument. Simple and reliable. */
"argv" | 
/**
 *  The prompt is pasted into the terminal once the harness has started and gone quiet. For
 *  harnesses with no prompt argument, and for prompts too long for a command line.
 */
"stdin";

/**  Emitted for every [`HostEvent`]. */
export type PtyHostEvent = HostEvent;

/**  Asks the webview to put the question to the user. It answers with [`app_quit`]. */
export type QuitRequested = {
	/**  The harness sessions still running, as ids the frontend can match to its tabs. */
	agents: string[],
};

/**
 *  Terminal output, sent over the channel as raw bytes rather than JSON: the webview receives
 *  an `ArrayBuffer` it can hand straight to xterm.js.
 * 
 *  The generated binding types this as `number[]` because specta only sees the `Vec<u8>`;
 *  `src/lib/ipc.ts` corrects that in one place.
 */
export type RawBytes = number[];

export type Relevance = 
/**  Does what the task asks for. */
"direct" | 
/**  Not the task itself, but plausibly needed for it. */
"supporting" | 
/**  Nothing to do with the task. */
"unrelated" | 
/**  The model had no clear read. */
"unsure";

export type Review = {
	files: FileReview[],
	/**
	 *  What the workspace was asked to do, as far as Yardsort knows: the first message of each
	 *  of its conversations. Without it, only the risk checks run.
	 */
	task: string | null,
	model: string,
	/**  A failure that left part of the review undone. */
	problem: string | null,
};

export type ReviewFlag = 
/**  A file whose name says it holds credentials. Decided here; its contents are never sent. */
"credentialsFile" | 
/**  The change adds a literal secret. */
"secret" | 
/**  Tests were removed, skipped, or made weaker. */
"weakensTests" | 
/**  A lint, type check or CI step was switched off. */
"disablesChecks";

export type Scope = "uncommitted" | "committed";

/**  Opaque, globally unique session identifier. */
export type SessionId = string;

export type SessionIdMode = 
/**  We choose the harness's session id up front, so resume is deterministic. */
"assigned" | 
/**
 *  The harness picks; we resume "the latest session in this directory", which is safe
 *  because every workspace has a directory of its own.
 */
"latestInCwd";

export type SessionInfo = {
	id: SessionId,
	program: string,
	args: string[],
	cwd: string | null,
	pid: number | null,
	size: TermSize,
	labels: { [key in string]: string },
	state: SessionState,
	/**
	 *  Whether the program has printed anything yet. With `idle_ms` this tells "still starting"
	 *  from "started and now waiting", without anyone parsing what it printed.
	 */
	hasOutput: boolean,
	/**  Producing output right now (see [`HostEvent::Busy`] / [`HostEvent::Quiet`]). */
	busy: boolean,
	/**
	 *  Milliseconds since the session last produced output (saturating). Drives "busy / waiting" indicators
	 *  without anyone having to parse what the program printed.
	 */
	idleMs: number,
};

export type SessionRecord = {
	id: string,
	workspaceId: string,
	harnessId: string,
	/**  The harness's display name, or its id if it is no longer configured. */
	harnessLabel: string,
	model: string | null,
	effort: string | null,
	title: string,
	forkedFrom: string | null,
	running: boolean,
	/**  The live PTY session, while running. */
	ptySessionId: string | null,
	exitCode: number | null,
	/**  Ended without an exit status: the app quit or crashed underneath it. */
	interrupted: boolean,
	/**  Milliseconds since the Unix epoch. */
	startedAt: number | null,
	endedAt: number | null,
	/**  Whether Resume / Fork can work, and why not when they cannot. */
	resumable: boolean,
	forkable: boolean,
	unavailableReason: string | null,
};

export type SessionState = { status: "running" } | { status: "exited"; exit: ExitInfo };

export type SettingsInfo = {
	/**  The "Open in editor" command; `None` tries the common editors in turn. */
	editorCommand: string | null,
	notifyWhenQuiet: boolean,
	checkForUpdates: boolean,
	workspaces: WorkspaceSettingsDto,
	defaultWorktreeRoot: string,
	/**  Set while `YARDSORT_WORKTREE_ROOT` overrides the setting. */
	worktreeRootOverride: string | null,
	filePath: string,
	/**  Why the settings file was ignored, if it was (it is kept, never overwritten). */
	problem: string | null,
};

export type SpawnRequest = {
	/**  Program to run. `None` starts the user's shell. */
	program: string | null,
	args?: string[],
	/**  Working directory. `None` means the home directory. Ignored when `workspace_id` is set. */
	cwd: string | null,
	/**
	 *  Run inside this workspace: the core looks up its folder (the webview never supplies
	 *  paths for this) and labels the session so it can be matched back to the workspace.
	 */
	workspaceId: string | null,
	/**  Run a harness instead of `program`. Requires `workspace_id`. */
	harness: HarnessRequest | null,
	size: TermSize,
};

export type Suggestion = {
	/**  The harness whose "Good at" fits best, when one clearly does. */
	harnessId: string | null,
	/**  The effort to offer, per harness id — the level depends on what each harness offers. */
	effortByHarness: { [key in string]: string },
};

export type TermSize = {
	cols: number,
	rows: number,
};

/**
 *  [`Thresholds`] as the webview sees them. The settings file keeps snake_case names people can
 *  read and edit; IPC is camelCase like everything else.
 */
export type ThresholdsDto = {
	flagAtPercent: number,
	offTaskAtPercent: number,
	suggestAtPercent: number,
	/**  What "Restore defaults" goes back to, so the form need not repeat them. */
	defaults: [number, number, number],
	/**  The lowest and highest either end may be. */
	range: [number, number],
};

/**
 *  A worktree git knows about that is not a workspace: made by hand, by another tool, or
 *  forgotten here. What the import dialog lists.
 */
export type UntrackedWorktree = {
	path: string,
	/**  `None` when detached. */
	branch: string | null,
};

export type UpdateStatus = {
	currentVersion: string,
	installKind: InstallKind,
	/**  The newer release, if there is one. */
	available: AvailableUpdate | null,
};

export type Workspace = {
	id: string,
	projectId: string,
	kind: WorkspaceKind,
	name: string,
	path: string,
	/**  What is checked out right now, asked of git at listing time. */
	head: HeadInfo | null,
	/**
	 *  The folder is gone though it should be there. It can be restored from its branch, or
	 *  deleted.
	 */
	missing: boolean,
	/**  Put away on purpose: no folder, but the branch and session history are kept. */
	archived: boolean,
	/**
	 *  There is no branch left to bring this workspace back from: its folder is not on disk and
	 *  its branch was deleted too (or it never had one). Only asked of git when the folder is
	 *  already gone, and a git that will not answer counts as "the branch is still there".
	 */
	branchGone: boolean,
};

/**  Something changed on disk in the watched workspace; ask again. */
export type WorkspaceFilesChanged = {
	workspaceId: string,
};

export type WorkspaceKind = 
/**  The project's own checkout. Always present, never deletable. */
"local" | 
/**  A git worktree on its own branch. */
"worktree";

export type WorkspaceSettingsDto = {
	/**  `None` uses `default_worktree_root`. */
	worktreeRoot: string | null,
	branchPrefix: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

