// @ts-nocheck
/* eslint-disable */
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	/**  Receives the result of a `YARDSORT_BENCH` run, prints it as one line of JSON and quits. */
	benchReport: (report: string) => __TAURI_INVOKE<void>("bench_report", { report }),
	projectsList: () => typedError<Project[], IpcError>(__TAURI_INVOKE("projects_list")),
	/**  Add the repository containing `path`. Fails with `not_a_git_repo` unless `init_git` is set. */
	projectOpen: (path: string, initGit: boolean) => typedError<AddedProject, IpcError>(__TAURI_INVOKE("project_open", { path, initGit })),
	projectAutomationGet: (projectId: string) => typedError<ProjectAutomation, IpcError>(__TAURI_INVOKE("project_automation_get", { projectId })),
	projectAutomationSave: (projectId: string, config: ProjectAutomation) => typedError<null, IpcError>(__TAURI_INVOKE("project_automation_save", { projectId, config })),
	workspaceRun: (workspaceId: string, size: TermSize) => typedError<SessionInfo, IpcError>(__TAURI_INVOKE("workspace_run", { workspaceId, size })),
	projectCreate: (name: string, parent: string) => typedError<AddedProject, IpcError>(__TAURI_INVOKE("project_create", { name, parent })),
	projectClone: (repository: string, name: string, parent: string) => typedError<AddedProject, IpcError>(__TAURI_INVOKE("project_clone", { repository, name, parent })),
	/**
	 *  Take a project off the list. With `keep_history` its workspaces and their conversations
	 *  wait for the folder to be opened again. Files on disk are never touched.
	 */
	projectRemove: (id: string, keepHistory: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("project_remove", { id, keepHistory })),
	projectsReorder: (orderedIds: string[]) => typedError<null, IpcError>(__TAURI_INVOKE("projects_reorder", { orderedIds })),
	uiStateLoad: () => typedError<{ [key in string]: string }, IpcError>(__TAURI_INVOKE("ui_state_load")),
	uiStateSave: (key: string, value: string) => typedError<null, IpcError>(__TAURI_INVOKE("ui_state_save", { key, value })),
	harnessesList: () => typedError<HarnessInfo[], IpcError>(__TAURI_INVOKE("harnesses_list")),
	/**
	 *  Save a harness definition. For a built-in only the differences from the shipped definition
	 *  are stored; saving one identical to it removes the override.
	 */
	harnessSave: (def: HarnessDef) => typedError<HarnessInfo[], IpcError>(__TAURI_INVOKE("harness_save", { def })),
	/**  Restore a built-in to its shipped definition, or delete a custom harness. */
	harnessReset: (id: string) => typedError<HarnessInfo[], IpcError>(__TAURI_INVOKE("harness_reset", { id })),
	/**  What would run for this — possibly unsaved — definition, with sample values filled in. */
	harnessPreview: (def: HarnessDef) => typedError<HarnessPreview, IpcError>(__TAURI_INVOKE("harness_preview", { def })),
	/**
	 *  Start this — possibly unsaved — definition in the home directory, with no prompt, to see
	 *  whether it comes up. The caller shows the session and closes it.
	 */
	harnessTest: (def: HarnessDef, size: TermSize) => typedError<SessionInfo, IpcError>(__TAURI_INVOKE("harness_test", { def, size })),
	settingsGet: () => typedError<SettingsInfo, IpcError>(__TAURI_INVOKE("settings_get")),
	settingsSaveWorkspaces: (workspaces: WorkspaceSettingsDto) => typedError<SettingsInfo, IpcError>(__TAURI_INVOKE("settings_save_workspaces", { workspaces })),
	settingsSaveGeneral: (editorCommand: string | null, notifyWhenQuiet: boolean, checkForUpdates: boolean) => typedError<SettingsInfo, IpcError>(__TAURI_INVOKE("settings_save_general", { editorCommand, notifyWhenQuiet, checkForUpdates })),
	projectBranches: (projectId: string) => typedError<BranchList, IpcError>(__TAURI_INVOKE("project_branches", { projectId })),
	/**
	 *  The core loop: make a worktree — on a new branch, or for an existing one — and start a harness in it with the user's
	 *  first message. Once prepared, the worktree is retained if the harness cannot start.
	 *  A script may have produced work, even if project settings change while it is running.
	 */
	workspaceCreate: (request: NewWorkspace) => typedError<CreatedWorkspace, IpcError>(__TAURI_INVOKE("workspace_create", { request })),
	/**  Remove a workspace's worktree. The branch is kept. Fails with `worktree_dirty` unless `force`. */
	workspaceDelete: (id: string, force: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("workspace_delete", { id, force })),
	workspaceChanges: (workspaceId: string) => typedError<ChangeSet, IpcError>(__TAURI_INVOKE("workspace_changes", { workspaceId })),
	workspaceDiff: (workspaceId: string, path: string, oldPath: string | null, scope: Scope) => typedError<FileDiff, IpcError>(__TAURI_INVOKE("workspace_diff", { workspaceId, path, oldPath, scope })),
	/**
	 *  One folder of the workspace's file tree (`dir` is relative; empty for the root). With
	 *  `show_ignored`, `.git` and ignored entries are included and flagged.
	 */
	workspaceFiles: (workspaceId: string, dir: string, showIgnored: boolean) => typedError<FileEntry[], IpcError>(__TAURI_INVOKE("workspace_files", { workspaceId, dir, showIgnored })),
	workspaceFile: (workspaceId: string, path: string) => typedError<Content, IpcError>(__TAURI_INVOKE("workspace_file", { workspaceId, path })),
	workspaceSaveFile: (workspaceId: string, path: string, expected: string, text: string) => typedError<null, IpcError>(__TAURI_INVOKE("workspace_save_file", { workspaceId, path, expected, text })),
	/**  Watch this workspace's files (replacing any previous watch); `None` stops watching. */
	workspaceWatch: (workspaceId: string | null) => typedError<null, IpcError>(__TAURI_INVOKE("workspace_watch", { workspaceId })),
	/**  Where the selected workspace stands with its remote: what it can commit, push and open. */
	workspacePublishState: (workspaceId: string, refresh: boolean) => typedError<PublishState, IpcError>(__TAURI_INVOKE("workspace_publish_state", { workspaceId, refresh })),
	/**
	 *  Commit everything the workspace has changed.
	 * 
	 *  Everything, because the panel offers no way to leave a file out — see
	 *  [`Git::commit_all`](crate::git::Git::commit_all). Nothing is staged until git has an identity
	 *  to commit with, so the common first failure does not leave a half-staged tree behind.
	 */
	workspaceCommit: (workspaceId: string, message: string) => typedError<PublishState, IpcError>(__TAURI_INVOKE("workspace_commit", { workspaceId, message })),
	/**  Push the workspace's branch, setting its upstream the first time. */
	workspacePush: (workspaceId: string) => typedError<PublishState, IpcError>(__TAURI_INVOKE("workspace_push", { workspaceId })),
	/**
	 *  Open a pull request for the workspace's branch, pushing first if it needs it.
	 * 
	 *  Pushing first because the alternative is a button that fails and tells you to press another
	 *  one: a branch the forge has never seen cannot have a pull request. With `gh` this ends on the
	 *  pull request; without it, on the forge's form with both branches already filled in.
	 */
	workspaceOpenPullRequest: (workspaceId: string, title: string, body: string, draft: boolean) => typedError<PullRequestOpened, IpcError>(__TAURI_INVOKE("workspace_open_pull_request", { workspaceId, title, body, draft })),
	/**
	 *  Merge a confirmed PR only if it is still open, still one of this workspace's, and still at
	 *  the head the user confirmed.
	 */
	workspaceMergePullRequest: (workspaceId: string, number: number, headOid: string, method: MergeMethod) => typedError<null, IpcError>(__TAURI_INVOKE("workspace_merge_pull_request", { workspaceId, number, headOid, method })),
	/**  Every pull request `gh` knows for a project, so each workspace row can show its own. */
	projectPullRequests: (projectId: string, refresh: boolean) => typedError<ProjectPullRequests, IpcError>(__TAURI_INVOKE("project_pull_requests", { projectId, refresh })),
	/**
	 *  Who would be asked to resolve pull request `number`'s conflicts, and how — for the
	 *  confirmation, before anything is sent. Reads the project's list, cached when it is fresh.
	 */
	workspaceConflictHelper: (workspaceId: string, number: number) => typedError<ConflictHelper, IpcError>(__TAURI_INVOKE("workspace_conflict_helper", { workspaceId, number })),
	/**
	 *  Ask the agent that opened pull request `number` to resolve its merge conflicts.
	 * 
	 *  The forge is asked first, not the list from a moment ago: a pull request that has stopped
	 *  conflicting, or whose conflicts GitHub has not worked out yet, is not worth an agent's turn.
	 *  It must be one this workspace opened, and `session_id` the conversation the user agreed to
	 *  ask — [`ConflictHelper::session_id`]. If another has become the one to ask since, nothing is
	 *  sent: the user said yes to that conversation, not to whichever.
	 */
	workspaceResolveConflicts: (workspaceId: string, number: number, sessionId: string, size: TermSize) => typedError<ConflictsAsked, IpcError>(__TAURI_INVOKE("workspace_resolve_conflicts", { workspaceId, number, sessionId, size })),
	/**  Who would write, for this workspace. `harnessId` is the agent the workspace is using. */
	draftStatus: (harnessId: string | null) => typedError<DraftStatus, IpcError>(__TAURI_INVOKE("draft_status", { harnessId })),
	workflowWriterStatus: () => typedError<WorkflowWriterStatus, IpcError>(__TAURI_INVOKE("workflow_writer_status")),
	workflowSaveWriter: (harnessId: string | null) => typedError<WorkflowWriterStatus, IpcError>(__TAURI_INVOKE("workflow_save_writer", { harnessId })),
	/**  Write a commit message for what the workspace has not committed. */
	draftCommitMessage: (workspaceId: string, harnessId: string | null) => typedError<string, IpcError>(__TAURI_INVOKE("draft_commit_message", { workspaceId, harnessId })),
	draftPullRequest: (workspaceId: string, harnessId: string | null) => typedError<DraftedPullRequest, IpcError>(__TAURI_INVOKE("draft_pull_request", { workspaceId, harnessId })),
	/**  Keep an Anthropic API key in the OS credential store. Never read back into the webview. */
	draftSaveKey: (key: string) => typedError<DraftStatus, IpcError>(__TAURI_INVOKE("draft_save_key", { key })),
	draftForgetKey: () => typedError<DraftStatus, IpcError>(__TAURI_INVOKE("draft_forget_key")),
	draftSaveSettings: (enabled: boolean, model: string) => typedError<DraftStatus, IpcError>(__TAURI_INVOKE("draft_save_settings", { enabled, model })),
	/**  Open a file (or the workspace folder, when `path` is `None`) in the user's editor. */
	openInEditor: (workspaceId: string, path: string | null) => typedError<null, IpcError>(__TAURI_INVOKE("open_in_editor", { workspaceId, path })),
	/**  Reveal a workspace entry, or open its nearest existing folder when it was deleted. */
	workspaceRevealFile: (workspaceId: string, path: string) => typedError<null, IpcError>(__TAURI_INVOKE("workspace_reveal_file", { workspaceId, path })),
	assistStatus: () => typedError<AssistStatus, IpcError>(__TAURI_INVOKE("assist_status")),
	/**
	 *  Save an API key, once TypeSafe confirms it works. It goes to the OS credential store and is
	 *  never sent back to the webview.
	 */
	assistSaveKey: (key: string) => typedError<AssistStatus, IpcError>(__TAURI_INVOKE("assist_save_key", { key })),
	assistForgetKey: () => typedError<AssistStatus, IpcError>(__TAURI_INVOKE("assist_forget_key")),
	/**  Ask TypeSafe whether the key in force still works. */
	assistTestKey: () => typedError<null, IpcError>(__TAURI_INVOKE("assist_test_key")),
	assistSaveSettings: (reviewChanges: boolean, suggestInComposer: boolean, sendProvenance: boolean, checkMemory: boolean, thresholds: ThresholdsDto) => typedError<AssistStatus, IpcError>(__TAURI_INVOKE("assist_save_settings", { reviewChanges, suggestInComposer, sendProvenance, checkMemory, thresholds })),
	/**
	 *  Check a workspace's changed files against what was asked, and for risky edits. Sends the
	 *  diffs of those files to TypeSafe.
	 */
	assistReview: (workspaceId: string) => typedError<Review, IpcError>(__TAURI_INVOKE("assist_review", { workspaceId })),
	/**
	 *  Suggest a harness and an effort for the message being typed. Sends the message and the
	 *  harnesses' "Good at" descriptions.
	 */
	assistSuggest: (message: string) => typedError<Suggestion, IpcError>(__TAURI_INVOKE("assist_suggest", { message })),
	/**
	 *  A page of a workspace's events, newest first: those before `before_seq` (or the newest,
	 *  when `None`), at most `limit` of them.
	 */
	activityTimeline: (workspaceId: string, beforeSeq: number | null, limit: number) => typedError<ActivityPage, IpcError>(__TAURI_INVOKE("activity_timeline", { workspaceId, beforeSeq, limit })),
	activityDiagnostics: () => typedError<ActivityDiagnostics, IpcError>(__TAURI_INVOKE("activity_diagnostics")),
	/**
	 *  Forget recorded activity — one workspace's, or all of it. Runs still going keep their row,
	 *  so their exit can still be matched; nothing about the processes themselves is touched.
	 */
	activityClear: (workspaceId: string | null) => typedError<null, IpcError>(__TAURI_INVOKE("activity_clear", { workspaceId })),
	/**
	 *  The reported writes for a workspace, as they stand now, and for each of `paths` — the
	 *  change list's files — whether its last write fell inside a tool call.
	 */
	workspaceProvenance: (workspaceId: string, paths: string[]) => typedError<Provenance, IpcError>(__TAURI_INVOKE("workspace_provenance", { workspaceId, paths })),
	/**
	 *  Assemble the packet for a workspace: the core's facts — the store's and git's — and, when
	 *  Assist is reviewing changes, its judgment of each file from the same review the Changes
	 *  list shows. Nothing new is sent for the packet: a review that is switched off, has no
	 *  key, or fails leaves the packet without a ranking, and the packet reads the same.
	 */
	workspaceHandoff: (workspaceId: string) => typedError<HandoffPacket, IpcError>(__TAURI_INVOKE("workspace_handoff", { workspaceId })),
	memoryGet: (projectId: string) => typedError<ProjectMemory, IpcError>(__TAURI_INVOKE("memory_get", { projectId })),
	/**  The user writes an entry: approved as written. */
	memoryWrite: (projectId: string, text: string) => typedError<ProjectMemory, IpcError>(__TAURI_INVOKE("memory_write", { projectId, text })),
	memoryEdit: (id: string, text: string) => typedError<ProjectMemory, IpcError>(__TAURI_INVOKE("memory_edit", { id, text })),
	memoryDecide: (id: string, decision: MemoryDecision) => typedError<ProjectMemory, IpcError>(__TAURI_INVOKE("memory_decide", { id, decision })),
	/**  Turn sharing a project's approved entries with its agents on or off. */
	memoryShare: (projectId: string, shared: boolean) => typedError<ProjectMemory, IpcError>(__TAURI_INVOKE("memory_share", { projectId, shared })),
	/**
	 *  How many proposals wait, per project that has any. Agents propose through `ys`, which writes
	 *  the database directly, so the window asks again when it regains focus and when activity lands.
	 */
	memoryWaiting: () => typedError<MemoryWaiting[], IpcError>(__TAURI_INVOKE("memory_waiting")),
	/**
	 *  Ask Jev whether each proposal waiting in a project repeats or contradicts an approved entry.
	 *  Only with the Assist switch on and a key in force; sends the proposals and the approved
	 *  entries, nothing else.
	 */
	memoryCheck: (projectId: string) => typedError<MemoryCheck[], IpcError>(__TAURI_INVOKE("memory_check", { projectId })),
	/**
	 *  A project's attempts, brought up to date first: every live workspace snapshotted, git asked
	 *  whether each branch was ahead or merged, and the pull requests the app already has cached
	 *  read for their state. Never a fetch: local history must not wait on the network, and the
	 *  publish panel keeps the cache current.
	 */
	outcomesGet: (projectId: string) => typedError<ProjectOutcomes, IpcError>(__TAURI_INVOKE("outcomes_get", { projectId })),
	/**
	 *  The user's word on an attempt — `kept`, `partly`, `discarded` — or `None` to take it back.
	 *  A workspace not yet recorded is snapshotted first, so any live one can be labelled.
	 */
	outcomeLabel: (id: string, label: string | null) => typedError<ProjectOutcomes, IpcError>(__TAURI_INVOKE("outcome_label", { id, label })),
	/**  Per-agent history across every project, for the composer: counted from outcomes only. */
	outcomesAgents: () => typedError<AgentOutcomes[], IpcError>(__TAURI_INVOKE("outcomes_agents")),
	settingsSaveActivity: (activity: ActivitySettingsDto) => typedError<SettingsInfo, IpcError>(__TAURI_INVOKE("settings_save_activity", { activity })),
	sessionsList: (workspaceId: string) => typedError<SessionRecord[], IpcError>(__TAURI_INVOKE("sessions_list", { workspaceId })),
	/**
	 *  How full a conversation's context is, as the agent last reported it, and what to type to
	 *  compact it. `None` when nothing was reported since it started or last compacted.
	 */
	sessionContext: (id: string) => typedError<{
	/**  Tokens the last request carried. */
	usedTokens: number,
	windowTokens: number,
	/**  `used / window`, rounded down, at most 100. */
	percent: number,
	/**  At or past [`SUGGEST_PERCENT`], and the harness has a command to compact with. */
	suggest: boolean,
	/**  What to type to compact, from the harness definition. */
	compactCommand: string | null,
} | null, IpcError>(__TAURI_INVOKE("session_context", { id })),
	/**  Continue a conversation whose process has ended, in a new terminal. */
	sessionResume: (id: string, size: TermSize) => typedError<SessionInfo, IpcError>(__TAURI_INVOKE("session_resume", { id, size })),
	/**  Start a copy of a conversation — running or not — that goes its own way from here. */
	sessionFork: (id: string, size: TermSize) => typedError<SessionInfo, IpcError>(__TAURI_INVOKE("session_fork", { id, size })),
	/**  Drop a record from the history. The harness's own copy of the conversation is not touched. */
	sessionForget: (id: string) => typedError<null, IpcError>(__TAURI_INVOKE("session_forget", { id })),
	/**
	 *  Put a workspace away: the worktree is removed, the branch and session history stay.
	 *  Fails with `worktree_dirty` unless `force`.
	 */
	workspaceArchive: (id: string, force: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("workspace_archive", { id, force })),
	/**  Bring back an archived workspace, or one whose folder disappeared, at its old path. */
	workspaceRestore: (id: string) => typedError<Workspace, IpcError>(__TAURI_INVOKE("workspace_restore", { id })),
	workspaceRename: (id: string, name: string) => typedError<Workspace, IpcError>(__TAURI_INVOKE("workspace_rename", { id, name })),
	/**
	 *  Worktrees of the project that are not workspaces — made by hand, by another tool, or
	 *  forgotten here — for the import dialog.
	 */
	projectUntrackedWorktrees: (projectId: string) => typedError<UntrackedWorktree[], IpcError>(__TAURI_INVOKE("project_untracked_worktrees", { projectId })),
	/**  Make workspaces of the untracked worktrees at `paths`. Nothing on disk is touched. */
	workspacesImport: (projectId: string, paths: string[]) => typedError<Workspace[], IpcError>(__TAURI_INVOKE("workspaces_import", { projectId, paths })),
	/**
	 *  Stop showing a workspace. Its folder and branch stay; with `keep_history` its conversations
	 *  do too, ready for the day it is imported again.
	 */
	workspaceForget: (id: string, keepHistory: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("workspace_forget", { id, keepHistory })),
	/**  With `reload`, the login shell is asked again first — for "I just installed it, look again". */
	preflight: (reload: boolean) => typedError<Preflight, IpcError>(__TAURI_INVOKE("preflight", { reload })),
	/**  Ask whether a newer release exists. Touches nothing on disk. */
	updateCheck: () => typedError<UpdateStatus, IpcError>(__TAURI_INVOKE("update_check")),
	/**
	 *  Download the update found by the last check, verify its signature, install it and restart.
	 *  Only for [`InstallKind::SelfUpdating`] copies.
	 */
	updateInstall: (progress: Channel<DownloadProgress>) => typedError<null, IpcError>(__TAURI_INVOKE("update_install", { progress })),
	/**  Where `ys` is, whether it is this version, and where Install would put it. */
	ysStatus: () => typedError<YsStatus, IpcError>(__TAURI_INVOKE("ys_status")),
	/**  Put `ys` on `PATH`. With `replace`, over a file that is not a `ys` — ask first. */
	ysInstall: (replace: boolean) => typedError<YsStatus, IpcError>(__TAURI_INVOKE("ys_install", { replace })),
	envInfo: (reload: boolean) => typedError<EnvInfo, IpcError>(__TAURI_INVOKE("env_info", { reload })),
	/**
	 *  What the app is talking to. Shown in the status bar, and the first thing worth knowing when
	 *  a terminal misbehaves.
	 */
	daemonStatus: () => typedError<DaemonStatus, IpcError>(__TAURI_INVOKE("daemon_status")),
	/**
	 *  The user's answer. `stop_agents` kills everything the daemon runs and stops it; otherwise the
	 *  agents are left to carry on and the app simply lets go of them.
	 */
	appQuit: (stopAgents: boolean) => typedError<null, IpcError>(__TAURI_INVOKE("app_quit", { stopAgents })),
	/**
	 *  Let the next close request ask again. Called when the user cancels, so that closing the
	 *  window later still puts the question.
	 */
	quitCancelled: () => typedError<null, IpcError>(__TAURI_INVOKE("quit_cancelled")),
	ptySpawn: (request: SpawnRequest) => typedError<SessionInfo, IpcError>(__TAURI_INVOKE("pty_spawn", { request })),
	/**  Stream a session into `output`: first a snapshot that repaints the terminal, then live bytes. */
	ptyAttach: (id: SessionId, output: Channel<RawBytes>) => typedError<number, IpcError>(__TAURI_INVOKE("pty_attach", { id, output })),
	ptyDetach: (id: SessionId, attachment: number) => typedError<null, IpcError>(__TAURI_INVOKE("pty_detach", { id, attachment })),
	ptyWrite: (id: SessionId, data: string) => typedError<null, IpcError>(__TAURI_INVOKE("pty_write", { id, data })),
	ptyResize: (id: SessionId, size: TermSize) => typedError<null, IpcError>(__TAURI_INVOKE("pty_resize", { id, size })),
	ptyKill: (id: SessionId) => typedError<null, IpcError>(__TAURI_INVOKE("pty_kill", { id })),
	/**  Kill (if needed) and forget a session. */
	ptyClose: (id: SessionId) => typedError<null, IpcError>(__TAURI_INVOKE("pty_close", { id })),
	ptyList: () => typedError<SessionInfo[], IpcError>(__TAURI_INVOKE("pty_list")),
	/**  Every workflow, built in and the user's, with how many runs of each are going now. */
	workflowList: () => typedError<WorkflowItem[], IpcError>(__TAURI_INVOKE("workflow_list")),
	/**  Check a file's text as it is being written: the editor's marks and the chart come from this. */
	workflowCheck: (text: string) => __TAURI_INVOKE<WorkflowCheck>("workflow_check", { text }),
	/**
	 *  Save a file: `path` is the user's file being edited, or `None` for a new one. Returns the id
	 *  it was saved under.
	 */
	workflowSave: (path: string | null, text: string) => typedError<string, IpcError>(__TAURI_INVOKE("workflow_save", { path, text })),
	/**
	 *  Copy a workflow into the user's folder. With no `asId`, a built-in's copy replaces it.
	 *  Returns the copy's id.
	 */
	workflowCopy: (id: string, asId: string | null) => typedError<string, IpcError>(__TAURI_INVOKE("workflow_copy", { id, asId })),
	/**  Delete one of the user's workflow files. The window asks first. */
	workflowRemove: (path: string) => typedError<null, IpcError>(__TAURI_INVOKE("workflow_remove", { path })),
	/**  Runs, newest first: of one workflow, or of all. */
	workflowRuns: (workflowId: string | null, limit: number) => typedError<WorkflowRun[], IpcError>(__TAURI_INVOKE("workflow_runs", { workflowId, limit })),
	/**  A run's steps, in file order. */
	workflowRunSteps: (runId: string) => typedError<WorkflowStepRun[], IpcError>(__TAURI_INVOKE("workflow_run_steps", { runId })),
	/**  What a run of `workflowId` in `workspaceId` would find, for the Run dialog to show. */
	workflowPreview: (workflowId: string, workspaceId: string) => typedError<RunPreview, IpcError>(__TAURI_INVOKE("workflow_preview", { workflowId, workspaceId })),
	/**  Start a run. The same checks as `ys workflow run`; the driver picks it up at once. */
	workflowStart: (workflowId: string, workspaceId: string, inputs: { [key in string]: string }) => typedError<string, IpcError>(__TAURI_INVOKE("workflow_start", { workflowId, workspaceId, inputs })),
	/**  Cancel a run. Agents it started keep running. */
	workflowCancel: (runId: string) => typedError<boolean, IpcError>(__TAURI_INVOKE("workflow_cancel", { runId })),
	/**
	 *  Have a model write a workflow from `description`, through Drafting: the agent the user has
	 *  in its non-interactive mode, or their Anthropic key. The answer is checked as a typed file
	 *  is, and sent back once with its problems when it has any.
	 * 
	 *  The agent runs in an empty git repository of the profile's own, not in any project of the
	 *  user's: a description is not a change to describe, and nothing here should read or touch
	 *  their work. A repository, not a bare folder, because Codex refuses to run outside one.
	 */
	workflowDescribe: (description: string) => typedError<Described, IpcError>(__TAURI_INVOKE("workflow_describe", { description })),
};

/** Events */
export const events = {
	activityChanged: makeEvent<ActivityChanged>("activity-changed"),
	ptyHostEvent: makeEvent<PtyHostEvent>("pty-host-event"),
	quitRequested: makeEvent<QuitRequested>("quit-requested"),
	sessionStarted: makeEvent<SessionStarted>("session-started"),
	workflowRunsChanged: makeEvent<WorkflowRunsChanged>("workflow-runs-changed"),
	workspaceFilesChanged: makeEvent<WorkspaceFilesChanged>("workspace-files-changed"),
};

/* Types */
/**  What a step does. Every string here may hold `{{ variables }}`; see [`template`]. */
export type Action = 
/**  Start a harness in the run's workspace, with a first message. */
{ action: "start_session"; harness: string; prompt: string | null; model: string | null; effort: string | null; skipMemory: boolean } | 
/**  Wait for a session to settle or to end. */
{ action: "wait_session"; session: SessionRef; until: Until; timeoutSecs: number | null } | 
/**  Paste a message into a live session once it is quiet. A busy agent is never written to. */
{ action: "send_to_session"; session: SessionRef; prompt: string; timeoutSecs: number | null } | 
/**  Wait for a review or a comment on the workspace's pull request, newer than the run. */
{ action: "wait_pr_activity"; kind: PrActivity; timeoutSecs: number | null } | 
/**  Tell the person who started the run. */
{ action: "notify"; title: string; body: string | null };

/**  New events were recorded for these workspaces; a timeline showing one should ask again. */
export type ActivityChanged = {
	workspaceIds: string[],
};

export type ActivityCounter = {
	name: string,
	count: number | null,
	lastAt: number | null,
	lastDetail: string | null,
};

/**  What there is, and what went wrong recording it. For Settings → General and bug reports. */
export type ActivityDiagnostics = {
	events: number | null,
	runs: number | null,
	/**  Where the daemon keeps exits for a closed window, and how many are waiting there. */
	spoolDir: string,
	spoolPending: number,
	/**  Where agents' hooks leave what they report, and how many entries are waiting there. */
	inboxDir: string,
	inboxPending: number,
	/**  The settings file Claude Code launches are given when capture is on. */
	claudeHooksFile: string,
	counters: ActivityCounter[],
};

/**
 *  One recorded fact, as the timeline shows it. Timestamps are epoch milliseconds; `payload`
 *  is the event's JSON, whose shape depends on `kind` (see the guide).
 */
export type ActivityEvent = {
	/**  Ingestion order: the cursor for paging, and the tie-breaker for display. */
	seq: number | null,
	id: string,
	schemaVersion: number,
	workspaceId: string,
	sessionId: string | null,
	runId: string | null,
	occurredAt: number | null,
	receivedAt: number | null,
	kind: string,
	/**
	 *  Who said so, how, and how sure to be: `yardsort` / `lifecycle` / `observed` for
	 *  everything recorded today.
	 */
	producer: string,
	method: string,
	fidelity: string,
	privacyClass: string,
	payload: string,
};

/**  One page of a workspace's timeline, newest first. */
export type ActivityPage = {
	events: ActivityEvent[],
	/**  Whether asking again with the last event's `seq` as `before` would find more. */
	hasMore: boolean,
};

/**  The activity switches, as Settings → General shows them. See `crate::activity`. */
export type ActivitySettingsDto = {
	/**  Record when a harness, shell or run command starts and exits in a workspace. */
	recordLifecycle: boolean,
	/**  Show the experimental activity timeline in a workspace. */
	showTimeline: boolean,
	/**  Give Claude Code launches hooks that report what the agent does, as metadata. */
	captureClaude: boolean,
	/**  Give Codex launches a `notify` program, and read each turn from its session file. */
	captureCodex: boolean,
	/**  Give OpenCode launches a plugin, through their environment, that reports what they do. */
	captureOpencode: boolean,
	/**  Read Grok's own session directory for Yardsort's launches of Grok. */
	captureGrok: boolean,
	/**  Give OMP launches an extension, on the command line, that reports what they do. */
	captureOmp: boolean,
	/**  The same for pi. */
	capturePi: boolean,
	/**  Give Cursor agent launches a plugin directory, on the command line, whose hooks report. */
	captureCursor: boolean,
};

/**  The result of adding a project: it may have been known already. */
export type AddedProject = {
	project: Project,
	alreadyKnown: boolean,
	/**  Set when the chosen folder was inside a repository and its root was added instead. */
	openedRootInstead: boolean,
	/**
	 *  Set when the folder was a project removed earlier with its history kept: it is back
	 *  with its workspaces and their conversations.
	 */
	revived: boolean,
};

export type AgentOutcomes = {
	harness: string,
	attempts: number,
	kept: number,
	keptByMerge: number,
	partly: number,
	discarded: number,
	/**  Attempts with an outcome. */
	known: number,
	/**  Whether `known` reaches the sample size below which nothing is said. */
	enough: boolean,
};

/**  Static facts about the running app, shown in the UI and useful in bug reports. */
export type AppInfo = {
	name: string,
	version: string,
	/**  `linux`, `macos` or `windows`. */
	os: string,
	arch: string,
	debug: boolean,
	dev: DevFlags,
};

export type AssistStatus = {
	keySource: KeySource,
	/**  The end of the key in force, so it can be told apart without being shown. */
	keyHint: string | null,
	/**  Why the credential store could not be used, if it could not. */
	problem: string | null,
	reviewChanges: boolean,
	suggestInComposer: boolean,
	/**  With the review, tell Jev who wrote each file, in the Changes list's words. */
	sendProvenance: boolean,
	/**  Check memory proposals for repeats of, and contradictions with, approved entries. */
	checkMemory: boolean,
	/**  How sure Jev must be before an answer becomes a badge or a suggestion. */
	thresholds: ThresholdsDto,
	/**  The model every request names. */
	model: string,
};

export type Attempt = {
	/**  The workspace's id when the attempt began; the workspace itself may be gone. */
	id: string,
	/**  Set while the workspace still exists. */
	workspaceId: string | null,
	workspaceName: string,
	branch: string | null,
	baseBranch: string | null,
	task: string | null,
	harnesses: string[],
	/**  What the user said, if anything. */
	label: string | null,
	/**  The outcome that counts: the label, or `kept` from a merge; `None` when unknown. */
	outcome: string | null,
	/**  `you` or `merge`, beside `outcome`. */
	outcomeSource: string | null,
	evidence: Evidence,
	createdAt: number | null,
};

export type AvailableUpdate = {
	version: string,
	/**  The release notes, as written on the release. */
	notes: string | null,
	/**  Where to read about it and download it by hand. */
	url: string,
};

export type BranchList = {
	branches: string[],
	/**  The branch to offer first: the remote's default, or the one checked out. */
	default: string | null,
	/**
	 *  Branches checked out in some worktree already. Git allows a branch in one place only, so
	 *  these cannot be opened as a workspace.
	 */
	checkedOut: string[],
};

export type ChangeKind = "added" | "modified" | "deleted" | "renamed" | 
/**  New and not yet known to git. */
"untracked" | "conflicted";

export type ChangeSet = {
	uncommitted: FileChange[],
	committed: FileChange[],
	/**
	 *  The branch `committed` is measured against; `None` when there is nothing to compare with
	 *  (the workspace *is* the base branch, or HEAD is detached).
	 */
	base: string | null,
};

/**  What CI says about a pull request's head commit, rolled up into the one thing a row can show. */
export type Checks = 
/**  Nothing is configured, or nothing has reported yet. */
"none" | "running" | "passing" | "failing";

/**  One commit, as much of it as a pull request needs. */
export type Commit = {
	subject: string,
	/**  Everything under the subject, with the blank line between them dropped. Often empty. */
	body: string,
};

/**  Who would be asked, for the confirmation. */
export type ConflictHelper = {
	/**
	 *  The conversation's record. The request goes to this one or to none: see
	 *  [`workspace_resolve_conflicts`].
	 */
	sessionId: string,
	harnessLabel: string,
	/**  The conversation's title, as its history lists it. */
	title: string,
	reach: Reach,
};

/**  The agent was asked. */
export type ConflictsAsked = {
	reach: Reach,
	/**  The terminal it is in: an existing tab for [`Reach::Type`], a new one otherwise. */
	session: SessionInfo,
};

export type Content = 
/**  The file does not exist on this side (added, or deleted). */
{ type: "absent" } | { type: "text"; text: string } | { type: "image"; mime: string; data: string } | { type: "notEditable"; reason: string } | { type: "binary" } | { type: "tooLarge"; bytes: number };

/**  A session's context, as last reported. */
export type ContextUsage = {
	/**  Tokens the last request carried. */
	usedTokens: number,
	windowTokens: number,
	/**  `used / window`, rounded down, at most 100. */
	percent: number,
	/**  At or past [`SUGGEST_PERCENT`], and the harness has a command to compact with. */
	suggest: boolean,
	/**  What to type to compact, from the harness definition. */
	compactCommand: string | null,
};

export type CreatedWorkspace = {
	workspace: Workspace,
	session: SessionInfo,
};

/**  What the app ended up talking to, as the status bar and a bug report want it. */
export type DaemonStatus = {
	/**
	 *  False when terminals are running inside the app instead — `YARDSORT_NO_DAEMON`, or a
	 *  daemon that could not be reached. They then die with the app, as they did before.
	 */
	running: boolean,
	version: string | null,
	pid: number | null,
	/**  Where the daemon listens, and where it writes when something goes wrong. */
	endpoint: string,
	logPath: string,
	/**  Why there is no daemon, when there should have been one. */
	problem: string | null,
	/**
	 *  Set when a daemon is running that this build cannot talk to — the app was updated
	 *  underneath agents that are still working. It says how many, so they can be asked about
	 *  rather than stopped behind the user's back.
	 */
	strandedSessions: number | null,
};

/**  A workflow a model wrote from a description, checked, for the editor. Nothing is saved. */
export type Described = {
	text: string,
	/**  What is still wrong with it, marked in the editor; empty when it checks out. */
	problems: Problem[],
	/**  How many answers it took: one, or two when the first had problems. */
	tries: number,
	/**  Who wrote it, in words. */
	writer: string,
};

/**
 *  Switches for measuring and debugging, read from the environment. Always empty in release
 *  builds.
 */
export type DevFlags = {
	/**
	 *  `YARDSORT_BENCH`: a shell script to run in a terminal while frame times are recorded;
	 *  the app prints the result and exits. See `docs/design/07-terminal-benchmarks.md`.
	 */
	bench: string | null,
	/**
	 *  `YARDSORT_BENCH_LATENCY`: time keystroke round trips in a terminal instead of running a
	 *  script, then print the result and exit. Takes precedence over `bench`.
	 */
	benchLatency: boolean,
	/**  `YARDSORT_RENDERER`: force the terminal renderer (`webgl` or `dom`). */
	renderer: string | null,
};

export type DownloadProgress = {
	downloaded: number,
	/**  `None` when the server did not say how big the download is. */
	total: number | null,
};

/**  Who would do the writing, and whether anyone can. */
export type DraftStatus = {
	/**  The setting: whether the user wants to be offered this at all. */
	enabled: boolean,
	/**  The button is actually shown — switched on *and* somebody able to answer. */
	available: boolean,
	/**  The harness that would write, when one can. */
	harness: string | null,
	/**  An Anthropic key is in force, so drafting works even with no agent able to write. */
	key: boolean,
	/**  The model that key would ask for. */
	model: string,
	/**  Why nothing can write, when nothing can. */
	problem: string | null,
};

/**  A pull request's title and description, from the commits the branch has made. */
export type DraftedPullRequest = {
	title: string,
	body: string,
};

/**  One workflow as the catalog lists it: runnable, or not, and why. */
export type Entry = {
	id: string,
	name: string,
	description: string | null,
	source: Source,
	/**  Empty when the workflow can run. */
	problems: Problem[],
	/**  The checked workflow; `None` when there are problems. */
	workflow: Workflow | null,
	/**  The file exactly as written. */
	text: string,
};

/**  What the launch environment looks like, for the status bar and for bug reports. */
export type EnvInfo = {
	source: EnvSource,
	shell: string,
	pathEntries: number,
	warning: string | null,
};

export type EnvSource = 
/**  Captured from the user's login shell. */
"loginShell" | 
/**  This process's own environment: always on Windows, and the fallback elsewhere. */
"process";

/**  What an attempt's outcome rests on, beside the outcome itself. */
export type Evidence = {
	/**  The branch was seen with commits of its own. */
	ahead: boolean,
	/**  After that, its work was seen in the base branch: a merge or a fast-forward. */
	mergedIntoBase: boolean,
	prNumber: number | null,
	/**  `open`, `merged` or `closed`. */
	prState: string | null,
	/**  `archived` or `deleted`, when the workspace ended. */
	ended: string | null,
};

export type ExitInfo = {
	code: number,
	success: boolean,
	/**  Name of the terminating signal, where the platform reports one. */
	signal: string | null,
};

export type FileChange = {
	/**  Path relative to the workspace root, with `/` separators. */
	path: string,
	/**  Where a renamed file used to live. */
	oldPath: string | null,
	kind: ChangeKind,
	/**  Lines added / removed. `None` for binary and untracked files. */
	additions: number | null,
	deletions: number | null,
};

export type FileDiff = {
	old: Content,
	new: Content,
};

export type FileEntry = {
	name: string,
	/**  Relative to the workspace root, with `/` separators. */
	path: string,
	isDir: boolean,
	/**  Excluded by the ignore rules (or `.git` itself). Only ever listed on request. */
	ignored: boolean,
};

/**  Every report about one workspace-relative path, oldest first, and what was observed of it. */
export type FileReports = {
	path: string,
	reports: WriteReport[],
	observed: ObservedWrite | null,
};

export type FileReview = {
	path: string,
	scope: Scope,
	/**  `None` when the workspace's task is not known, or the file was not checked. */
	relevance: Relevance | null,
	flags: ReviewFlag[],
	/**  Why this file was not looked at, if it was not. */
	notChecked: string | null,
	/**  What Jev was told about who wrote the file, word for word, when that was sent. */
	told: string | null,
};

/**  Which forge a host is, as far as the shape of its URLs goes. */
export type ForgeKind = "github" | "gitlab" | "bitbucket" | 
/**
 *  Gitea, Forgejo, and anything else self-hosted: assumed to speak GitHub's URL shapes,
 *  which the Gitea family does. A wrong guess costs a link that 404s, not data.
 */
"unknown";

export type GitStatus = {
	path: string | null,
	/**  As `git --version` prints it, e.g. `git version 2.55.0`. */
	version: string | null,
};

/**
 *  A handoff packet: what Yardsort recorded about a workspace, as the opening prompt for the
 *  next agent there. See `yardsort_core::activity::handoff`.
 */
export type HandoffPacket = {
	/**  Markdown, for the composer's message box: the user reads and edits it before sending. */
	text: string,
	/**  How many agent runs and events stand behind it, for the line above the box. */
	runs: number,
	events: number,
};

export type HarnessDef = {
	/**  Stable key, recorded with sessions. */
	id: string,
	label: string,
	command: string,
	/**  Always passed. */
	baseArgs: string[],
	/**
	 *  What puts the agent in its "auto" permission mode: it acts on its own but keeps a check on
	 *  risky actions, rather than asking about everything or nothing. Passed only while
	 *  [`Self::auto_mode`] is on. Empty means the harness has no such mode.
	 */
	autoArgs?: string[],
	/**
	 *  Start every interactive session — new, resumed or forked — with [`Self::auto_args`].
	 *  Off unless the user turns it on: how much an agent may do unasked is their call.
	 */
	autoMode?: boolean,
	modelArgs: string[],
	effortArgs: string[],
	sessionArgs: string[],
	promptArgs: string[],
	/**
	 *  How to run this agent **non-interactively**, with `{prompt}` for the question: the
	 *  print / exec mode every agent has. Yardsort uses it to have the agent write a commit
	 *  message or a pull request — see [`crate::draft`]. Empty means this harness cannot, which
	 *  is the honest default for one we know nothing about.
	 */
	writeArgs?: string[],
	resumeArgs: string[],
	forkArgs: string[],
	/**  Effort levels to offer. Empty hides the picker. */
	efforts: string[],
	/**  Model suggestions. Free text is always accepted: names change faster than we ship. */
	models: string[],
	promptTransport: PromptTransport,
	sessionIdMode: SessionIdMode,
	/**
	 *  With the `stdin` transport: how long the harness must have been quiet, after printing
	 *  something, before the prompt is pasted.
	 */
	stdinReadyMs: number,
	/**  Disabled harnesses stay configured but are not offered. */
	enabled: boolean,
	/**
	 *  In the user's words, what this harness is good at. Assist uses it to suggest a harness
	 *  for a task; harnesses without one are never suggested. Empty for every built-in: which
	 *  agent suits which work is the user's call, not ours.
	 */
	strengths?: string,
	/**
	 *  What to type into the agent to have it summarise its conversation and free its context,
	 *  e.g. `/compact`. Offered when the agent reports a context that is nearly full — see
	 *  [`crate::activity::context`]. `None` for an agent that has no such command or does not
	 *  report its context.
	 */
	compactCommand?: string | null,
};

/**  A harness definition plus whether its command can be found on this machine. */
export type HarnessInfo = {
	/**  Where `command` resolved to on the user's `PATH`; `None` if it is not installed. */
	resolvedPath: string | null,
	/**  Ships with Yardsort (as opposed to one the user added). */
	builtin: boolean,
	/**  A built-in whose definition the user has changed. */
	modified: boolean,
} & HarnessDef;

/**  The exact command lines a definition produces, for the settings form to show. */
export type HarnessPreview = {
	resolvedPath: string | null,
	start: string[],
	resume: string[],
	fork: string[],
	/**  Why this definition cannot be saved as it stands, if it cannot. */
	problem: string | null,
};

/**  Which harness to start, and with what. */
export type HarnessRequest = {
	id: string,
	/**  `None` or empty: let the harness use its own default. */
	model: string | null,
	effort: string | null,
	/**  The first message. `None` or empty just opens the harness. */
	prompt: string | null,
	/**
	 *  The first message is a handoff packet Yardsort assembled (see `activity::handoff`),
	 *  not the user's own task: it is sent like any prompt, but the session's record keeps no
	 *  prompt, so the workspace's task — what Assist and the next packet read — stays the
	 *  user's words.
	 */
	handoff?: boolean,
	/**
	 *  Leave the project's memory out of this launch's first message, though the project shares
	 *  it. The composer's per-launch opt-out; see `crate::memory`.
	 */
	skipMemory?: boolean,
};

export type HarnessStatus = {
	id: string,
	label: string,
	command: string,
	enabled: boolean,
	/**  Where the command was found; `None` if it is not installed (or not on `PATH`). */
	path: string | null,
	/**  How to get it. Known for the built-in harnesses only. */
	install: InstallHint | null,
};

export type HeadInfo = {
	/**  Branch name, or the abbreviated commit when detached. */
	label: string,
	detached: boolean,
	/**  The branch has no commits yet. */
	unborn: boolean,
};

/**  Host-wide notifications, delivered to the sink given to [`crate::PtyHost::new`]. */
export type HostEvent = 
/**  The session's process ended and all of its output has been delivered. */
{ type: "exited"; id: SessionId; exit: ExitInfo } | 
/**  The session started producing output after being quiet. */
{ type: "busy"; id: SessionId } | 
/**
 *  The session has printed nothing for the host's quiet period: whatever runs in it is
 *  probably waiting for input. `busy_ms` is how long the burst of activity lasted, which
 *  lets a client tell an agent finishing minutes of work from the echo of a keystroke.
 */
{ type: "quiet"; id: SessionId; busyMs: number };

/**  Something asked of the person starting a run, before it starts. */
export type Input = {
	id: string,
	kind: InputKind,
	/**  What the question says. The id when the file gives none. */
	label: string,
	required: boolean,
	default: string | null,
	/**  The choices of a `choice` input; empty for the others. */
	options: string[],
};

export type InputKind = 
/**  One of the harnesses set up in Yardsort, picked the way the composer picks one. */
"harness" | "text" | "choice";

export type InstallHint = {
	/**  An install command for the current OS; shown for the user to copy, never executed. */
	command: string,
	/**  The project's own install instructions, for every other way. */
	url: string,
};

/**  How this copy of the app gets new versions. */
export type InstallKind = 
/**  It can download and install an update itself. */
"selfUpdating" | 
/**  A package manager owns the files; the user updates through it. */
"packageManager" | 
/**  A development build. Never updates. */
"development";

/**
 *  The one error shape that crosses IPC: a stable `code` for the UI to branch on and a
 *  human-readable `message` to show.
 */
export type IpcError = {
	code: string,
	message: string,
};

export type KeySource = "none" | 
/**  Saved from Settings, in the OS credential store. */
"keychain" | 
/**  `TYPESAFE_API_KEY`, from the environment Yardsort runs in. */
"environment";

/**  What Jev said about one proposal. */
export type MemoryCheck = {
	id: string,
	/**  It says what an approved entry already says. */
	repeats: boolean,
	/**  It says the opposite of an approved entry, or something that cannot also be true. */
	contradicts: boolean,
};

export type MemoryDecision = "approve" | "reject" | "revoke" | "restore";

export type MemoryEntry = {
	id: string,
	/**  The first 8 characters of the id, as agents see it cited. */
	shortId: string,
	text: string,
	/**  `candidate`, `approved`, `rejected` or `revoked`. */
	state: string,
	/**  `user` or `agent`. */
	author: string,
	/**  Where it came from, in words: "the user", or "claude in fix-login". */
	from: string,
	createdAt: number | null,
	updatedAt: number | null,
	history: MemoryHistoryItem[],
};

/**  One change to an entry. */
export type MemoryHistoryItem = {
	at: number | null,
	/**  `proposed`, `written`, `approved`, `edited`, `rejected`, `revoked` or `restored`. */
	action: string,
	/**  `user` or `agent`. */
	by: string,
	/**  The text an edit replaced. */
	previousText: string | null,
};

/**  How many proposals wait in a project. */
export type MemoryWaiting = {
	projectId: string,
	count: number,
};

export type MergeMethod = "squash" | "merge" | "rebase";

/**
 *  GitHub's answer to "can this be merged without conflicts". It works it out lazily, after a
 *  push to either side, so `Unknown` is an ordinary answer for a while and not an error.
 */
export type Mergeable = "mergeable" | "conflicting" | "unknown";

export type NewWorkspace = {
	projectId: string,
	/**  `None` starts from the project's default branch. */
	baseBranch: string | null,
	/**  Open this existing branch instead of creating a new one; `base_branch` is then ignored. */
	existingBranch: string | null,
	harness: HarnessRequest,
	size: TermSize,
};

/**  One tool call that was executing when the file was last written. */
export type ObservedMatch = {
	runId: string,
	harnessId: string | null,
	tool: string | null,
	from: number | null,
	/**  `None` while the tool call is still running. */
	to: number | null,
};

/**  The file's last write, by its own clock, fell inside one or more tool calls' windows. */
export type ObservedWrite = {
	at: number | null,
	matches: ObservedMatch[],
};

export type PrActivity = "review" | "comment" | "any";

export type PrFacts = {
	number: number,
	url: string,
	title: string,
};

export type Preflight = {
	git: GitStatus,
	harnesses: HarnessStatus[],
	env: EnvInfo,
	/**  `linux`, `macos` or `windows`: install advice differs. */
	os: string,
	/**  The `ys` command. Optional: it never stands in the way of `ready`. */
	ys: YsStatus,
	/**  Nothing stands between the user and their first workspace. */
	ready: boolean,
};

/**  One thing wrong with a file, where it is. */
export type Problem = {
	/**  1-based. `None` when the problem is the file as a whole. */
	line: number | null,
	column: number | null,
	message: string,
};

export type Project = {
	id: string,
	name: string,
	rootPath: string,
	/**
	 *  The folder is gone (deleted, moved, or on an unmounted drive). The project is kept so it
	 *  reappears by itself if the folder does; the user can remove it.
	 */
	missing: boolean,
	workspaces: Workspace[],
};

export type ProjectAutomation = {
	copyFiles: string[],
	setup: ProjectCommand | null,
	run: ProjectCommand | null,
};

export type ProjectCommand = {
	program: string,
	args: string[],
};

/**  A project's memory, as the view shows it. */
export type ProjectMemory = {
	projectId: string,
	/**  Whether approved entries go into this project's agents' first messages. */
	shared: boolean,
	/**  Oldest first. */
	entries: MemoryEntry[],
	/**  The section a first message would get now, or `None` when nothing would be added. */
	preview: string | null,
};

export type ProjectOutcomes = {
	projectId: string,
	/**  Newest first. */
	attempts: Attempt[],
	agents: AgentOutcomes[],
	/**  How many known outcomes an agent needs before its history says anything. */
	minSample: number,
};

/**  What `gh` says about one project's pull requests. */
export type ProjectPullRequests = {
	/**
	 *  `gh` is installed. Without it there are no pull request numbers and no check results
	 *  anywhere in the app — which is a supported state, not a fault.
	 */
	gh: boolean,
	pullRequests: PullRequest[],
	/**  Why the list is empty when it should not have been. */
	problem: string | null,
	/**  The problem is that nobody is logged in, which has its own one-line fix. */
	loggedOut: boolean,
	/**
	 *  Each workspace's own pull requests, by number, newest first: see
	 *  [`pull_requests_from`]. A workspace can have several — a branch reused after its pull
	 *  request merged, or a second branch its agent opened one from. Absent for a workspace
	 *  git could not be asked about.
	 */
	workspaces: { [key in string]: number[] },
};

export type PromptTransport = 
/**  The prompt is an argument. Simple and reliable. */
"argv" | 
/**
 *  The prompt is pasted into the terminal once the harness has started and gone quiet. For
 *  harnesses with no prompt argument, and for prompts too long for a command line.
 */
"stdin";

/**
 *  Which of a workspace's files its agents said they wrote, and which runs could have said so.
 *  Joined to git's own change list by the Changes panel; nothing here is stored.
 */
export type Provenance = {
	files: FileReports[],
	runs: RunCoverage[],
};

/**  Emitted for every [`HostEvent`]. */
export type PtyHostEvent = HostEvent;

/**
 *  Where a workspace stands: what it can commit, push and open, and what happened to it.
 * 
 *  Deliberately not the *count* of uncommitted files — the changes panel already has that list
 *  and asking git twice for the same thing is how the two come to disagree.
 */
export type PublishState = {
	/**  `None` when HEAD is detached or unborn: there is nothing to push or open. */
	branch: string | null,
	/**  What a pull request would merge into. */
	base: string | null,
	/**  Who commits would be by, or `None` when git has no identity configured. */
	identity: string | null,
	/**  The remote to push to, `origin` for choice. */
	remote: string | null,
	/**  The remote read as a repository on a forge; `None` for a remote that is a local path. */
	repo: Repo | null,
	/**  What the branch tracks, once it has been pushed. */
	upstream: string | null,
	/**
	 *  Commits the remote does not have: measured against the upstream once there is one, and
	 *  against the base branch before that.
	 */
	ahead: number,
	behind: number,
	/**
	 *  Those commits, newest first — what a pull request would be about. Their bodies come
	 *  too: a well-written commit is a well-written pull request, and the dialog uses it.
	 */
	unpushed: Commit[],
	pullRequest: PullRequest | null,
	/**
	 *  Opening one makes sense: a branch that is not its own base, on a forge, without a pull
	 *  request already open. Decided here rather than in the webview, which holds no truth.
	 */
	canOpen: boolean,
	/**  `gh` is installed, so a pull request can be opened without leaving Yardsort. */
	gh: boolean,
	/**
	 *  Why there is no forge answer, when there should have been one. Not a failure — it is why
	 *  the row shows no number, which is worth saying somewhere the user is already looking.
	 */
	problem: string | null,
	/**  That reason is "log in first", which has a one-line fix worth printing. */
	loggedOut: boolean,
};

/**  A pull request, as much of it as a workspace row and the panel need. */
export type PullRequest = {
	number: number,
	url: string,
	title: string,
	/**  The branch it would merge, which is how a workspace finds its own. */
	branch: string,
	state: PullRequestState,
	draft: boolean,
	checks: Checks,
	details: PullRequestDetails | null,
};

export type PullRequestCheck = {
	name: string,
	state: Checks,
};

/**  Detail shared by the sidebar card and toolbar, from the same project-wide query. */
export type PullRequestDetails = {
	base: string,
	headOid: string,
	additions: number,
	deletions: number,
	review: string,
	updatedAt: string,
	checks: PullRequestCheck[],
	/**  Whether it merges cleanly into its base, as the forge last worked it out. */
	mergeable: Mergeable,
};

/**  A pull request that now exists, or the form to fill in to make one. */
export type PullRequestOpened = {
	url: string,
	/**  `gh` opened it. When false the URL is the forge's own form, to finish in a browser. */
	created: boolean,
};

export type PullRequestState = "open" | "merged" | "closed";

/**  Asks the webview to put the question to the user. It answers with [`app_quit`]. */
export type QuitRequested = {
	/**  The harness sessions still running, as ids the frontend can match to its tabs. */
	agents: string[],
};

/**
 *  Terminal output, sent over the channel as raw bytes rather than JSON: the webview receives
 *  an `ArrayBuffer` it can hand straight to xterm.js.
 * 
 *  The generated binding types this as `number[]` because specta only sees the `Vec<u8>`;
 *  `src/lib/ipc.ts` corrects that in one place.
 */
export type RawBytes = number[];

/**  How the message reaches the agent. */
export type Reach = 
/**  It is running and quiet: the message is typed into it. */
"type" | 
/**  Its process has ended: the conversation is resumed and the message typed in once ready. */
"resume" | 
/**  The conversation cannot be continued: a new one of the same agent is started with it. */
"start";

export type Relevance = 
/**  Does what the task asks for. */
"direct" | 
/**  Not the task itself, but plausibly needed for it. */
"supporting" | 
/**  Nothing to do with the task. */
"unrelated" | 
/**  The model had no clear read. */
"unsure";

/**  A repository on a forge, as read out of a remote URL. */
export type Repo = {
	host: string,
	/**  The owner, which on GitLab may itself contain `/` for subgroups. */
	owner: string,
	name: string,
	kind: ForgeKind,
};

export type Review = {
	files: FileReview[],
	/**
	 *  What the workspace was asked to do, as far as Yardsort knows: the first message of each
	 *  of its conversations. Without it, only the risk checks run.
	 */
	task: string | null,
	model: string,
	/**  A failure that left part of the review undone. */
	problem: string | null,
};

export type ReviewFlag = 
/**  A file whose name says it holds credentials. Decided here; its contents are never sent. */
"credentialsFile" | 
/**  The change adds a literal secret. */
"secret" | 
/**  Tests were removed, skipped, or made weaker. */
"weakensTests" | 
/**  A lint, type check or CI step was switched off. */
"disablesChecks" | 
/**
 *  A substantive change no agent reported making, in a workspace whose agents were
 *  reporting what they wrote. Only asked when the provenance facts are sent.
 */
"unaccounted";

/**  What a run is about. A workspace run knows the workspace, its branch and its pull request. */
export type RunContext = "workspace";

/**  One of the workspace's agent runs and how it was asked to report, or `None` if it was not. */
export type RunCoverage = {
	runId: string,
	harnessId: string | null,
	startedAt: number | null,
	endedAt: number | null,
	capture: string | null,
	/**  Whether a `None` capture is known to mean the run was not reporting. */
	captureKnown: boolean,
};

/**  What the Run dialog shows before starting: what the run would find. */
export type RunPreview = {
	/**  The workflow works with the workspace's pull request. */
	needsPullRequest: boolean,
	/**  Found: the workspace's open pull request. */
	pullRequest: PrFacts | null,
	/**  Why there is none to use, when one is needed. */
	pullRequestProblem: string | null,
	/**  The workflow talks to the workspace's own agent. */
	needsOrigin: boolean,
	/**  Variables the run will render as nothing, and why. A run still goes ahead. */
	empty: string[],
};

export type Scope = "uncommitted" | "committed";

/**  Opaque, globally unique session identifier. */
export type SessionId = string;

export type SessionIdMode = 
/**  We choose the harness's session id up front, so resume is deterministic. */
"assigned" | 
/**
 *  The harness picks; we resume "the latest session in this directory", which is safe
 *  because every workspace has a directory of its own.
 */
"latestInCwd";

export type SessionInfo = {
	id: SessionId,
	program: string,
	args: string[],
	cwd: string | null,
	pid: number | null,
	size: TermSize,
	labels: { [key in string]: string },
	state: SessionState,
	/**
	 *  Whether the program has printed anything yet. With `idle_ms` this tells "still starting"
	 *  from "started and now waiting", without anyone parsing what it printed.
	 */
	hasOutput: boolean,
	/**  Producing output right now (see [`HostEvent::Busy`] / [`HostEvent::Quiet`]). */
	busy: boolean,
	/**
	 *  Milliseconds since the session last produced output (saturating). Drives "busy / waiting" indicators
	 *  without anyone having to parse what the program printed.
	 */
	idleMs: number,
};

export type SessionRecord = {
	id: string,
	workspaceId: string,
	harnessId: string,
	/**  The harness's display name, or its id if it is no longer configured. */
	harnessLabel: string,
	model: string | null,
	effort: string | null,
	title: string,
	forkedFrom: string | null,
	running: boolean,
	/**  The live PTY session, while running. */
	ptySessionId: string | null,
	exitCode: number | null,
	/**  Ended without an exit status: the app quit or crashed underneath it. */
	interrupted: boolean,
	/**  Milliseconds since the Unix epoch. */
	startedAt: number | null,
	endedAt: number | null,
	/**  Whether Resume / Fork can work, and why not when they cannot. */
	resumable: boolean,
	forkable: boolean,
	unavailableReason: string | null,
};

/**  Which session a step means. */
export type SessionRef = 
/**  The workspace's most recent live harness session: the agent whose work the run is about. */
"origin" | 
/**  The session an earlier `start_session` step started, by that step's id. */
{ step: string };

/**  A workflow run started a session in a workspace: the window should show it as a tab. */
export type SessionStarted = {
	workspaceId: string,
	sessionId: string,
};

export type SessionState = { status: "running" } | { status: "exited"; exit: ExitInfo };

export type SettingsInfo = {
	/**  The "Open in editor" command; `None` tries the common editors in turn. */
	editorCommand: string | null,
	notifyWhenQuiet: boolean,
	checkForUpdates: boolean,
	workspaces: WorkspaceSettingsDto,
	defaultWorktreeRoot: string,
	/**  Set while `YARDSORT_WORKTREE_ROOT` overrides the setting. */
	worktreeRootOverride: string | null,
	filePath: string,
	/**  Why the settings file was ignored, if it was (it is kept, never overwritten). */
	problem: string | null,
	activity: ActivitySettingsDto,
};

/**  Where a workflow came from. */
export type Source = 
/**  Compiled into Yardsort. Read-only; duplicate it to change it. */
{ kind: "builtIn" } | 
/**  A file in the user's workflows directory. */
{ kind: "file"; path: string; 
/**
 *  This file's id is a built-in's, so it is used instead. Removing it brings the
 *  built-in back.
 */
replacesBuiltIn: boolean };

export type SpawnRequest = {
	/**  Program to run. `None` starts the user's shell. */
	program: string | null,
	args?: string[],
	/**  Working directory. `None` means the home directory. Ignored when `workspace_id` is set. */
	cwd: string | null,
	/**
	 *  Run inside this workspace: the core looks up its folder (the webview never supplies
	 *  paths for this) and labels the session so it can be matched back to the workspace.
	 */
	workspaceId: string | null,
	/**  Run a harness instead of `program`. Requires `workspace_id`. */
	harness: HarnessRequest | null,
	size: TermSize,
};

/**  One node of the graph. */
export type Step = {
	id: string,
	/**
	 *  The steps that must have succeeded before this one starts. Steps whose needs are all met
	 *  run together.
	 */
	needs: string[],
} & Action;

export type Suggestion = {
	/**  The harness whose "Good at" fits best, when one clearly does. */
	harnessId: string | null,
	/**  The effort to offer, per harness id — the level depends on what each harness offers. */
	effortByHarness: { [key in string]: string },
};

export type TermSize = {
	cols: number,
	rows: number,
};

/**
 *  [`Thresholds`] as the webview sees them. The settings file keeps snake_case names people can
 *  read and edit; IPC is camelCase like everything else.
 */
export type ThresholdsDto = {
	flagAtPercent: number,
	offTaskAtPercent: number,
	suggestAtPercent: number,
	/**  What "Restore defaults" goes back to, so the form need not repeat them. */
	defaults: [number, number, number],
	/**  The lowest and highest either end may be. */
	range: [number, number],
};

/**  What starts a run, and what a run is about. */
export type Trigger = {
	kind: TriggerKind,
	context: RunContext,
};

/**  Only a person starts a run in this version. Schedules and forge events come later. */
export type TriggerKind = "manual";

export type Until = 
/**  Quiet, or a finished turn where the harness reports turns. */
"settled" | "exited";

/**
 *  A worktree git knows about that is not a workspace: made by hand, by another tool, or
 *  forgotten here. What the import dialog lists.
 */
export type UntrackedWorktree = {
	path: string,
	/**  `None` when detached. */
	branch: string | null,
};

export type UpdateStatus = {
	currentVersion: string,
	installKind: InstallKind,
	/**  The newer release, if there is one. */
	available: AvailableUpdate | null,
};

/**  A workflow file, checked and ready to run. */
export type Workflow = {
	id: string,
	name: string,
	description: string | null,
	version: number,
	trigger: Trigger,
	inputs: Input[],
	steps: Step[],
};

/**  What checking a file's text found. */
export type WorkflowCheck = {
	/**  Step id to its current YAML source line, for chart navigation. */
	stepLines: { [key in string]: number },
	/**  The workflow, when the text checks out. */
	workflow: Workflow | null,
	id: string | null,
	problems: Problem[],
};

/**  A workflow as the sidebar and the view list it. */
export type WorkflowItem = {
	/**  Its runs queued or running now, in any workspace. */
	activeRuns: number,
} & Entry;

/**  One run, as the view lists it. */
export type WorkflowRun = {
	id: string,
	workflowId: string,
	workflowName: string,
	workspaceId: string | null,
	workspaceName: string,
	/**  `queued`, `running`, `succeeded`, `failed` or `cancelled`. */
	status: string,
	/**  `app` or `cli`. */
	requestedBy: string,
	error: string | null,
	inputs: { [key in string]: string },
	pullRequest: PrFacts | null,
	createdAt: number | null,
	startedAt: number | null,
	endedAt: number | null,
};

/**
 *  Runs changed: one was queued, moved on, finished or cancelled. The window reloads what it
 *  shows of them.
 */
export type WorkflowRunsChanged = Record<string, never>;

/**  One step of a run. */
export type WorkflowStepRun = {
	stepId: string,
	action: string,
	/**  `pending`, `running`, `waiting`, `succeeded`, `failed`, `skipped` or `cancelled`. */
	status: string,
	startedAt: number | null,
	endedAt: number | null,
	outputs: { [key in string]: string },
	note: string | null,
};

/**  Workflow writing has its own harness preference; commit and PR writers stay workspace-based. */
export type WorkflowWriterStatus = {
	harnessId: string | null,
	status: DraftStatus,
};

export type Workspace = {
	id: string,
	projectId: string,
	kind: WorkspaceKind,
	name: string,
	path: string,
	/**  What is checked out right now, asked of git at listing time. */
	head: HeadInfo | null,
	/**
	 *  The folder is gone though it should be there. It can be restored from its branch, or
	 *  deleted.
	 */
	missing: boolean,
	/**  Put away on purpose: no folder, but the branch and session history are kept. */
	archived: boolean,
	/**
	 *  There is no branch left to bring this workspace back from: its folder is not on disk and
	 *  its branch was deleted too (or it never had one). Only asked of git when the folder is
	 *  already gone, and a git that will not answer counts as "the branch is still there".
	 */
	branchGone: boolean,
};

/**  Something changed on disk in the watched workspace; ask again. */
export type WorkspaceFilesChanged = {
	workspaceId: string,
};

export type WorkspaceKind = 
/**  The project's own checkout. Always present, never deletable. */
"local" | 
/**  A git worktree on its own branch. */
"worktree";

export type WorkspaceSettingsDto = {
	/**  `None` uses `default_worktree_root`. */
	worktreeRoot: string | null,
	branchPrefix: string,
};

/**
 *  What one agent run reported about one changed file. See
 *  `yardsort_core::activity::provenance`.
 */
export type WriteReport = {
	runId: string | null,
	harnessId: string | null,
	producer: string,
	method: string,
	fidelity: string,
	firstAt: number | null,
	lastAt: number | null,
	/**  Reports, not lines: how many times the agent said it wrote the file. */
	writes: number,
};

/**  How this copy of the app puts `ys` on `PATH`. */
export type YsMethod = 
/**  The package installed it along with the app. Nothing to do. */
"packaged" | 
/**  A symlink into the app bundle (macOS). */
"link" | 
/**  A copy, refreshed when the app is updated (AppImage, Windows). */
"copy";

export type YsStatus = {
	/**  The app's version; the `ys` that came with it is the same one. */
	version: string,
	method: YsMethod,
	/**
	 *  The `ys` that came with this copy of the app. `None` for a build without one: a
	 *  development build before `cargo build -p yardsort-cli`, or one bundled by hand.
	 */
	bundled: string | null,
	/**  Where Install puts it. `None` when the package already did. */
	target: string | null,
	/**  Something is at `target` already. */
	installed: boolean,
	/**  The folder `target` is in is on the login shell's `PATH`, so a terminal will find it. */
	targetOnPath: boolean,
	/**  The `ys` a terminal finds, if any. */
	found: string | null,
	/**  What `found --version` says. `None` if it is not a `ys` at all. */
	foundVersion: string | null,
	/**  `found` is the one this app ships or installed. */
	foundIsOurs: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

